---
mine-probability:
  1: 1/2
  3: 1/3
  12: 1/3
  13: 1/5
  14: 1/60
  15: 1/45
  16: 1/12
  21: 1/18
  24: 50/100
  48: 40/100
  56: 1/90
  73: 1/24
  82: 25/100
  87: 20/100
  129: 1/72
...